baseURL = 'https://shifu-totto.github.io/shift-log/'
title = 'Shift-log'
author = 'Shifu-totto'
languageCode = 'ja'
DefaultContentLanguage = 'ja'
hasCJKLanguage = true
theme = 'Blonde'
enableRobotsTXT = true
enableInlineShortcodes = true

[params]
  base_color = 'bg-gray-800'
  description = '技術とゲームと雑記'
  paginator_pages = 5
  archive_dropdown = 'false'
  tagsLimit = 20
  recentLimit = 5
  darkmode = 'light'

  [params.post]
    thumbnail = true
    noimage = true
    thumbnail_height = 'lg:h-44'
    thumbnail_width = 'lg:w-auto'
    description = '130'

  [params.widgets]
    display = true
    mobile = true
    widgets = ['search', 'archive', 'category', 'tags', 'social', 'recent']

  [params.share]
    enable = true

  [[params.social]]
    name = 'GitHub'
    url = 'https://github.com/shifu-totto'
    icon = 'github'

  [[params.social]]
    name = 'Twitter / X'
    url = 'https://x.com/Shifu_totto'
    icon = 'twitter-x'

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'ホーム'
    url = '/'
    weight = 1

  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 2

  [[menu.main]]
    identifier = 'contact'
    name = 'Contact'
    url = '/contact/'
    weight = 3

[taxonomies]
  category = 'categories'
  tag = 'tags'
  archive = 'archives'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[security]
  [security.exec]
    allow = ['^(dart-)?sass$', '^go$', '^git$', '^node$', '^postcss$', '^tailwindcss$']
